# Ligne indispensable pour que CocoaPods comprenne les commandes Flutter
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'generated_plugin_registrant.rb')

platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Cette ligne utilise maintenant le lien chargé plus haut
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end